# Generated by Django 3.0.3 on 2020-02-15 23:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ProgramLibrary', '0002_auto_20200215_2312'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='description',
            field=models.IntegerField(default=0),
        ),
    ]
