# Generated by Django 3.0.3 on 2020-02-18 16:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ProgramLibrary', '0003_activity_description'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Activity',
        ),
    ]
