# Generated by Django 3.0.3 on 2020-02-19 00:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ProgramLibrary', '0005_auto_20200219_0003'),
    ]

    operations = [
        migrations.AlterField(
            model_name='section',
            name='program',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='ProgramLibrary.Program'),
        ),
    ]
