# Generated by Django 3.0.3 on 2020-02-19 00:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ProgramLibrary', '0007_auto_20200219_0033'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='section',
            name='program',
        ),
        migrations.DeleteModel(
            name='Activity',
        ),
        migrations.DeleteModel(
            name='Section',
        ),
    ]
