# Generated by Django 3.0.3 on 2020-02-18 03:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ProgramLibrary', '0003_activity_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('description', models.TextField()),
                ('image', models.ImageField(upload_to='images/')),
                ('order_index', models.IntegerField()),
                ('program', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='section_program', to='ProgramLibrary.Program')),
            ],
            options={
                'ordering': ('order_index',),
            },
        ),
    ]
