# Generated by Django 3.0.3 on 2020-02-18 03:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Activity', '0001_initial'),
        ('Section', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='section',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activity_section', to='Section.Section'),
        ),
    ]
